spring:
  application:
    name: mc-friends

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/friends_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:

    change-log: classpath:/db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

client:
  auth: "http://mc-auth:8081"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${instance.id:${random.value}}
    prefer-ip-address: true

server:
  port: 8092

springdoc:
  packagesToScan: com.example.mcfriends.controller

management:
  endpoints:
    web:
      exposure:

        include: "*"
  metrics:
    export:
      prometheus:

