spring:
  application:
    name: FRIEND-SERVICE

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/friends_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:

    change-log: classpath:/db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: userRegistered:com.socialnetwork.auth.dto.kafka.UserRegisteredEvent
client:
  auth: "http://mc-auth:8081"
services:
  account:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:8080/internal/account}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8092

springdoc:
  packagesToScan: com.example.mcfriends.controller

logging:
  level:
    # Корневой уровень
    root: INFO
    
    # Наш код - основной уровень
    com.example.mcfriends: INFO
    # Сервисы - подробная отладка
    com.example.mcfriends.service: DEBUG
    # Репозитории - подробная отладка
    com.example.mcfriends.repository: DEBUG
    
    # Spring Framework
    org.springframework.web: INFO
    org.springframework.security: WARN
    org.springframework.kafka: INFO
    
    # Hibernate - SQL запросы
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
    # Kafka
    org.apache.kafka: WARN

  # Паттерн логов
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  # Запись в файл
  file:
    name: logs/mc-friends.log
    max-size: 10MB
    max-history: 30


management:
  endpoints:
    web:
      exposure:

        include: "*"
  metrics:
    export:
      prometheus:

