scrape_configs:
  - job_name: 'mc-friends-service' # Имя вашего микросервиса
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      # Замените 'хост_вашего_сервиса' на IP-адрес/имя хоста, где запущен 'mc-friends'.
      # Если Prometheus и сервис запущены локально или в одной Docker-сети:
      - targets: ['localhost:8083']